service: kinesis-and-errors

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:PutRecord
        - kinesis:PutRecords
      Resource:
        Fn::GetAtt:
          - Stream
          - Arn
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - Fn::GetAtt:
            - Table
            - Arn


functions:
  createErrors:
    handler: handler.createErrors
    size: 128
    environment:
      STREAM_NAME:
        Ref: Stream
  subscriber:
    handler: handler.subscriber
    size: 128
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - Stream
              - Arn
    environment:
      TABLE_NAME:
        Ref: Table


resources:
  Resources:
    Stream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${self:provider.stage}-${self:service}-stream
        RetentionPeriodHours: 24
        ShardCount: 1
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-${self:service}-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1